# -*- coding: utf-8 -*-
"""Tarea 10

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j18pqfUV0ZWkaZZKl_6MFeBIONunRP_E
"""

# el resultado del consumo en el dia 5 es 9
import numpy as np

consumo = np.array([
    [10, 12, 11, 13, 14, 15, 16],
    [9, 11, 10, 12, 13, 14, 15],
])

consumo_viernes_hogar1 = consumo[1, 4]
print("Consumo del hogar 1 el viernes:", consumo_viernes_hogar1)

consumo_domingo_ultimos2 = consumo[-2:, 6]
print("Consumo el domingo de los últimos 2 hogares:", consumo_domingo_ultimos2)

consumo_ultimos3_domingo = np.array(consumo)[-3:, 6]
print(consumo_ultimos3_domingo)

fines_semana = np.array(consumo)[:, 5:7]
promedio_fines_semana = np.mean(fines_semana)
print(promedio_fines_semana)  # Resultado: 10.5

desviaciones = np.std(np.array(consumo), axis=0)
dia_mayor_desviacion = np.argmax(desviaciones)
print("Día con mayor desviación estándar:", dia_mayor_desviacion)
print("Desviación estándar de cada día:", desviaciones)

import numpy as np

consumo = np.array([
    [10, 12, 11, 13, 14, 15, 16],
    [9, 11, 10, 12, 13, 14, 15],
])

print(consumo[1, 4])                    # Consumo del hogar 1 el viernes
print(consumo[-2:, 6])                 # Domingo de los últimos 2 hogares

if consumo.shape[0] >= 3:
    print(consumo[-3:, 6])             # Domingo de los últimos 3 hogares (si hay)

print(np.mean(consumo[:, 5:7]))        # Promedio fin de semana
print(np.argmax(np.std(consumo, 0)))   # Día con mayor desviación
print(np.std(consumo, 0))              # Desviaciones por día
print(np.sum(consumo[0] * 1.1))        # Total hogar 0 con 10% aumento